### ISSUE TITLE
Plot of new Lux data

### ISSUE THREAD

**Issue by thanatosmin** [meyer-lab/FcgR-binding#5]
We will need to present a new plot of the data from Anja since this isn't published previously. This can be processed data with the raw data presented in a supplementary table.

**Comment by thanatosmin** [comment]
#6

**Comment by thanatosmin** [comment]
Resolved by #6

**Comment by thanatosmin** [comment]
This plot still needs error bars added at some point. Glad to help with this if how to implement this is unclear.

**Comment by robbobbinett** [comment]
Error bars added. The x-axis labels ("TNP-X-BSA") are difficult to read at default figure size; however, based on how bug we want the figure in the paper, I thought it would be best to mess with figure size later. Otherwise, the only thing that can be done with this figure is hiding the "zero bars."

**Comment by thanatosmin** [comment]
Exactly the right plan. Is this merged into main? Once that's done this can be closed.

**Comment by robbobbinett** [comment]
Yes sir, it is merged to master. About to delete the extra branch.

Also, I am super sorry I did not tell you; I will be arriving early tomorrow and leaving to get a haircut, coming back, and then leaving early again, like at 4:30. Is that ok?

Ryan
